
import { Fallacy } from './types';

// Detect logical fallacies in user arguments
export const detectFallacies = (text: string): Fallacy[] => {
  const fallacies: Fallacy[] = [];
  const lowerText = text.toLowerCase();
  
  // Ad Hominem detection
  if (lowerText.includes('stupid') || 
      lowerText.includes('idiot') || 
      lowerText.includes('dumb') ||
      /they (are|seem) (just )?ignorant/i.test(text)) {
    fallacies.push({
      name: 'Ad Hominem',
      description: 'You attacked the character or personal traits of an opponent rather than addressing their argument.',
      improvement: 'Focus on addressing the argument itself rather than the person making it.'
    });
  }
  
  // Straw Man detection
  if (lowerText.includes('clearly you think') || 
      lowerText.includes('you would say') || 
      lowerText.includes('your side believes') ||
      lowerText.includes('you people always')) {
    fallacies.push({
      name: 'Straw Man',
      description: 'You misrepresented someone\'s argument to make it easier to attack.',
      improvement: 'Ensure you are addressing the actual position held by your opponent, not a simplified or distorted version.'
    });
  }
  
  // False Dichotomy detection
  if (lowerText.includes('either') && lowerText.includes('or') && 
      (lowerText.includes('only two') || 
       lowerText.includes('only choice') || 
       lowerText.includes('must choose'))) {
    fallacies.push({
      name: 'False Dichotomy',
      description: 'You presented only two options when more exist.',
      improvement: 'Consider if there might be additional options or nuanced positions between the extremes.'
    });
  }
  
  // Appeal to Emotion detection
  if (lowerText.includes('think of the children') || 
      lowerText.includes('how would you feel') || 
      lowerText.includes('heartbreaking') ||
      lowerText.includes('devastating')) {
    fallacies.push({
      name: 'Appeal to Emotion',
      description: 'You attempted to manipulate an emotional response in place of a valid argument.',
      improvement: 'While emotions have their place, strengthen your argument with logic and evidence.'
    });
  }
  
  // Appeal to Authority detection
  if (/experts all (agree|say)/i.test(text) || 
      /studies have (shown|proven)/i.test(text) && 
      !lowerText.includes('according to') && 
      !lowerText.includes('research by')) {
    fallacies.push({
      name: 'Appeal to Authority',
      description: 'You used the opinion of an authority figure to support your argument without providing specific sources.',
      improvement: 'Cite specific studies or experts and explain their relevance to your point.'
    });
  }
  
  // Hasty Generalization detection
  if (lowerText.includes('all people') || 
      lowerText.includes('everyone knows') || 
      lowerText.includes('always') ||
      lowerText.includes('never')) {
    fallacies.push({
      name: 'Hasty Generalization',
      description: 'You drew a broad conclusion from a small sample.',
      improvement: 'Be more specific about the scope of your claims and acknowledge exceptions when they exist.'
    });
  }
  
  return fallacies;
};

// Generate AI responses based on the debate context
export const generateAiResponse = async (
  topic: string, 
  aiPosition: 'for' | 'against',
  messageType: 'introduction' | 'response',
  userMessage: string
): Promise<string> => {
  // In a real implementation, this would call an actual AI service
  // For this demo, we'll use pre-written responses based on the topic and position
  
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  if (messageType === 'introduction') {
    return getIntroductionMessage(topic, aiPosition);
  } else {
    return getResponseMessage(topic, aiPosition, userMessage);
  }
};

const getIntroductionMessage = (topic: string, aiPosition: 'for' | 'against'): string => {
  const position = aiPosition === 'for' ? 'support' : 'oppose';
  
  return `I'll be taking the position to ${position} "${topic}". Let's have a constructive debate! I'll present facts and logical arguments from this perspective to help you strengthen your own arguments.

What's your opening argument?`;
};

const getResponseMessage = (topic: string, aiPosition: 'for' | 'against', userMessage: string): string => {
  // These are mock responses for demonstration purposes
  // In a real implementation, these would be generated by an AI model
  
  const responses: {[key: string]: {for: string[], against: string[]}} = {
    "Universal Basic Income": {
      for: [
        "While I understand your concerns about costs, research by the Roosevelt Institute suggests UBI could actually grow the economy by 2.5 trillion dollars by 2025. It's not just an expense, but an investment in economic stimulation as people spend their basic income on necessities.",
        "You mention dependency, but studies from UBI pilots in Canada and Finland showed no significant decrease in work motivation. Instead, recipients reported better mental health and ability to seek better employment, addressing the very economic mobility you're concerned about."
      ],
      against: [
        "Universal Basic Income sounds appealing in theory, but the economic reality is troubling. The Tax Foundation estimates implementing a $12,000 annual UBI would cost $2.8 trillion annually—nearly 70% of our current federal budget. This would either require massive tax increases or unsustainable deficit spending.",
        "While I appreciate the humanitarian intent, UBI could create perverse incentives. Labor force participation declined during the Finland UBI experiment, and economists like Casey Mulligan have pointed out that guaranteed income often reduces economic mobility rather than enhancing it."
      ]
    },
    "Climate Change Solutions": {
      for: [
        "I respect your economic concerns, but addressing climate change is actually economically beneficial. The Global Commission on the Economy and Climate found that decisive climate action could deliver $26 trillion in economic benefits through 2030. Renewable energy now employs more Americans than fossil fuels, with solar jobs growing 167% over the past decade.",
        "Your point about developing nations is important, but climate policies can be designed equitably. The Paris Agreement includes financial mechanisms specifically to help developing countries adopt clean technology. Climate justice means ensuring solutions don't disadvantage vulnerable populations."
      ],
      against: [
        "While climate concerns are legitimate, many proposed solutions are economically devastating. The U.S. Chamber of Commerce calculated that the Green New Deal would cost American households $70,000 in the first year alone. We need to balance environmental goals with economic realities.",
        "Climate regulations disproportionately harm developing nations that rely on affordable fossil fuels for economic growth. Before industrialization, 90% of humanity lived in extreme poverty; access to cheap energy has been crucial for raising living standards. We should pursue technological innovation rather than restrictive policies."
      ]
    }
  };
  
  // Default responses for topics not in our predefined list
  const defaultResponses = {
    for: [
      `I understand your perspective, but there are several compelling reasons to support ${topic}. Research has shown positive outcomes in regions that have implemented similar approaches, including economic benefits and social improvements.`,
      `While I respect your concerns, the evidence supporting ${topic} is substantial. Multiple studies indicate that the benefits outweigh the potential drawbacks, particularly when we consider long-term societal impacts.`
    ],
    against: [
      `I appreciate your enthusiasm, but there are serious problems with ${topic} that must be addressed. Analysis of similar implementations shows concerning patterns of unintended consequences that outweigh the proposed benefits.`,
      `Your points are thoughtful, but the data presents a different picture. Critics have identified fundamental flaws in the assumptions behind ${topic}, including economic inefficiencies and potential negative social impacts.`
    ]
  };
  
  const topicResponses = responses[topic] || defaultResponses;
  const positionResponses = topicResponses[aiPosition];
  
  // Return a random response from the available options
  return positionResponses[Math.floor(Math.random() * positionResponses.length)];
};
